const keywordData = [
  {
    "순위": 1,
    "제목": "[단독]'엄지척' 김경 'CES 출입증 사적유용' 의혹도 본격 수사 - 노컷뉴스",
    "추천점수": 17.0,
    "키워드": "단독, 의혹",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiUkFVX3lxTE9yVjFGTW94U05CYXFfVk1MYlcwUmpzZW1SZ3kyZjdpWWpmR1NPcDFOU2RFVWJlMlNwZS1BbE1aQ3JIekJucUNVWWNXbzc3LTFGTEE?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 2,
    "제목": "“세금 환급 대상”이라더니…국세청처럼 보이는 조회 알림, 소비자 혼란",
    "추천점수": 14.0,
    "키워드": "환급, 세금",
    "카테고리": "사회",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/020/0003695786?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 3,
    "제목": "[속보] 경북 경주 문무대왕면 산불 국가소방동원령 발령",
    "추천점수": 13.0,
    "키워드": "속보, 국가",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/052/0002311978?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "https://n.news.naver.com/article/055/0001331299?ntype=RANKING",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 4,
    "제목": "'CCTV 확인했다, 좋더냐?' 음식 빼돌린 배달 기사 논란 - 네이트",
    "추천점수": 13.0,
    "키워드": "CCTV, 논란",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE1LazBqVG1zMzJmb1RmM3ZIQy1zOHN3dnF1NXJWQUxxUkRJa3RfMUJ2SFdKSHA2MTZFd28xS3NZQnQ4Z2VLZmF6M2I0Y19PR2d1aHpn?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 5,
    "제목": "[속보] 경북 경주 문무대왕면 산불 국가소방동원령 발령",
    "추천점수": 13.0,
    "키워드": "속보, 국가",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/052/0002311978?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 6,
    "제목": "[속보]정원오 “서울시장 출마 채비 마쳤다” - 문화일보",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiUEFVX3lxTFBGdGV4UFBpZ1ZhazFFVFRCODZZaUFEU01CMUpTNU5IejA5Ym1CS0ZvcFpVRTc1djU0OFRWMDZBMXRJRzVGZXVFQnpnLWx5aXBE?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTE9SRWdlMFdyZXFvVl9QUS16OGJYSzZZV0N6VXpWLW1yUDBSbHVOTU5qMVlGTHlNU0EyTUpXdlZLRHBlOHp1ODU1QXJ5aDN5VHM?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 7,
    "제목": "서울-부산 왕복에 월급이 통째로…'달리는 궁전' 문화 충격[뉴스속오늘] - 머니투데이",
    "추천점수": 10.0,
    "키워드": "충격",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMia0FVX3lxTE1YU1RnVndNdlhPNl9wWG1HQnlhNXdyWXVka0RGSV9QSGN6X1U1Rm1NNUFBS0x0dFFZSWtnaTZTN0RKa0NqczVZaVJJX1JhR1ZxdHVxSUE5S2Fna2pvTHdnTjlFZG53X1JUWmNB?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 8,
    "제목": "함소원, 재결합 고민 중 충격 발언에 어질 “딸보다 진화 더 좋아하는 듯”(동치미)[핫피플] - v.daum.net",
    "추천점수": 10.0,
    "키워드": "충격",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTFB6WjNfaXZpNF9BS2tsSHFvUU44WnprTWNIck5Wb0Y5bkNaVzkwTkt0cWkxal9DVTJaOHdoanczSnJraGp5RXR2bEh0Mm5HOGM?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 9,
    "제목": "[단독]이재용 회장, 룰라 브라질 대통령 만난다…남미 시장 확대 - 머니투데이",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibEFVX3lxTE5jY1R3SUVrOXNaRGJBOXhuYlZ0S3pYT3A4TFlEUVEyb1hkY0tOd0VLOElnb0NMcnpxbjJ6alRZN3U4MUcwbVpkQy1BRXhuMHFSUlkzQlo4Y0k0Q3lrSl9kM1N1NGl0LVZ6VE4wdg?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 10,
    "제목": "[속보] 정원오 성동구청장 \"서울시장 출마 채비 마쳤다\" - 뉴스1",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTE9SRWdlMFdyZXFvVl9QUS16OGJYSzZZV0N6VXpWLW1yUDBSbHVOTU5qMVlGTHlNU0EyTUpXdlZLRHBlOHp1ODU1QXJ5aDN5VHM?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiUEFVX3lxTFBGdGV4UFBpZ1ZhazFFVFRCODZZaUFEU01CMUpTNU5IejA5Ym1CS0ZvcFpVRTc1djU0OFRWMDZBMXRJRzVGZXVFQnpnLWx5aXBE?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 11,
    "제목": "[속보] 정청래 “특검 추천, 당 인사검증 실패로 대통령께 누 끼쳐” - 경향신문",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1xaXR0bFFnUmE3ZWFvN1FSOFBTQlJJc3pOYW0yVGE5UHZ3aUlvVS1jSEhBX3o3ZWxFMHVuM2VkdWtEZlVRWTVmNW1KZzBaOVg5V2hpbkFUbVNPUdIBX0FVX3lxTFAwQklmcTNPdk81bWpseVk5cjZFYWVZNGlNZUxxb3pDV0t3S3Nwc3FtVG4wb3RKS3l0bUdnSE5OcnpXWjgwaFJpRENhYjg0X2EwQ0lxQW9FM2lPb2lINnRR?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 12,
    "제목": "\"중국 호텔 침대 몰카에 내가…\" 수천명에 생중계까지 '충격' - 네이트",
    "추천점수": 10.0,
    "키워드": "충격",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE8tRUV0OGotci03Q3FkX2FCb2ZkSmRxUHBFQTZvWlRQOGVuSVh0MUYteENxWmdqWDBLdTlNbmlsd2EtWl96eTdKU3YtdHlRalhUbTI0?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 13,
    "제목": "법원 “충분한 조사 없이 진실규명 신청 각하한 진화위 위법” - 조선일보",
    "추천점수": 10.0,
    "키워드": "진실, 조사",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMihwFBVV95cUxPbmJRelpVTkRpWWFlNklBbkZNTVZyWjRPb3VCTUFwTl9SaXpLTlkyb3ZNQjNWSnFNbTNPbjNrMjBFX1RCOTBDbkRRT1RLeDFoVWtQUFRSaW81c0pud014clM4QmpRaVpjVUNHd1U0N1dkNXVwMXktZjBJNVNmUzN1X1FkYXpxcknSAZsBQVVfeXFMTmFmZEJDaDhGTDZROHBJTDFDdjdLNlczVE0yNjhHZV9xa3ZBcHpBZUVMcy1XZWNHVXU3ZVk4c1RJQVBnTFhzR0xnQmJLLWQ1cUNQc0FMdnJZVHpha1hBRFl0X0ptZ1VadDZUNzlZN3F6OFoyVHBwWENPVmhCU0ZfUTJkQ2pydUNvc0E3MUVBNU8zT1ZrTWc5Y09kWlU?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE83UXFOVjI2dnBLREpwREFNbTc3el9DLTZ4eU51dWdhdWF3N3F0ckVwYXlwcm9pUnlfcjRFQjQwdTlvejhHZ0J0eTNURWRnOXBIcEctag?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 14,
    "제목": "박나래 주사이모, 경찰 조사 후 '그알'에 분노⋯\"유서 공개한 제작진, 사과하라\" - 이투데이",
    "추천점수": 9.0,
    "키워드": "공개, 조사, 분노",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE1lLXQyVUxzZDBLWGpOdWdKMVJMZXJfUmltZlAwT0dQV2pQVXM3ZGxqczlWLV9CNTNQWHdDa2czcGdFSjZmNVNiTG5hcVBrXzcxNlFESw?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 15,
    "제목": "\"정치 금지\"라더니… 머스크의 X, '우파 계정'이 공모전 상금 싹쓸이 - 뉴시스",
    "추천점수": 7.0,
    "키워드": "금지",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE9DLTFYQ2xWaHhzcTVjS1ZGeVdjRkM2dGk4NlRPUVltY3BmNncyYjJvRGoxREJ5YzVyNWJnY0J6eHh2b3FEVS1ENEpXN0JITTU4cU12aWpKb2R0c3RYbVFCWtIBeEFVX3lxTFAtSlN2TV9CYkVjU3o1cG9wV2c1aW5VcmJtUkNvaHhFLTlRdWJyZUllZV9IMzZNblhXX2NIRFM4cWFzclBGbGNsYi0wdVJzM2Z0R2p0Uy1pcHpaemtUU2gwUUdnbjhzdG9zR3NDaG85cnFiNWt5YTVKUQ?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 16,
    "제목": "일본 오늘 총선…자민당 ‘절대 안정 다수’ 확보 여부 주목 - edaily.co.kr",
    "추천점수": 7.0,
    "키워드": "절대",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMigAFBVV95cUxNSXRna0J6ZXlvRGNJeEh5RHdXRUgzcHVic0k3cC16ODdSeENjNWVHcHZXTjFPOFo4UmJPc0haTGs3eGZzOXZiN2traUtzazJWWk5Ib3JsaGhoX192WndnOWFtQVNLZUdHQ1NqS3N6dFE4SnVBdmZRZXlkb1ZXYzg1Uw?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 17,
    "제목": "“무조건 많이 하라고”…‘배기성 아내’ 이은비, ‘난임 성지’서 49금 질문 폭격 - 매일경제",
    "추천점수": 7.0,
    "키워드": "무조건",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE5nQ3lFSmVHd3RVX25GeFBaYXdyM1JRem9jY05nRWptbkRtZERYVGdWV3gxbXoyTE1mYTdTcFUxejFlMHBiMTg0UERKQi1paWdmaDQ4MUI1UlE0akp3QzBqdzR0OGFuZw?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 18,
    "제목": "‘결혼 9년 차’ 배기성♥이은비, 2세 도전…“무조건 많이 하고”(조선의사랑꾼) - 스포츠동아",
    "추천점수": 7.0,
    "키워드": "무조건",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibkFVX3lxTE51UVNUVU9zWHJub0c0aUYyX3dybWl1QUUtODhmU2lLUTJkNi13eVpUbndVSlpoYTZhOEk4eEpnR3NnOFdJdXVwUU9vVmpIRklkeElvcjA3WUtxcHp2bndlMkkwdjZnbW5rN2otaWNR?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 19,
    "제목": "\"무조건 많이 하라던데\"…아내 돌직구에 고개 숙인 배기성 - 머니투데이",
    "추천점수": 7.0,
    "키워드": "무조건",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMic0FVX3lxTE5FVVVNRExubDBCcUhITG5YelNXT2tzMWp6QTJTbXBqTG9qaldaVVJFZUE2STlxa0Jla2pEeS10TXBTcmh5eHZuYjZLQW80VjRvTEFOakh2ZEhhZzlLdWpScmlXR25wdXpqZ0tQQWdOUzlUc0k?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 20,
    "제목": "중국, 가상자산 통제 고삐…‘위안화 스테이블코인’ 역외발행 금지 - 이투데이",
    "추천점수": 7.0,
    "키워드": "금지",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE1yeDR5Q0JZcWhXcWo5dmszbVpXcjZ0OWZRZmY0WW9vZm1nSUhFT0t6YVhiQkg4ajhOZGsyRU00bVMzRFQ4VFRSRUxYdVh1SnZNc0QyUQ?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 21,
    "제목": "'배기성♥' 이은비, 난임 성지서 간절함 폭발 \"임신하려면 무조건 많이 깊숙하게…\"(사랑꾼) - 네이트",
    "추천점수": 7.0,
    "키워드": "무조건",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFB5WUFPVkVuVUozN2VuWnptaURVeEthWDVPanpYOFhvSm5CQUpqRUs2N19sRERmT0JaTU13R3JhdzlVeXhqZHJvM3FMZGlkM29HTmow?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 22,
    "제목": "퇴사 통보에 영업비밀 '슬쩍'…17년 '독점 판권' 날아가",
    "추천점수": 7.0,
    "키워드": "비밀",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/055/0001331272?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 23,
    "제목": "잘 나가는 거물들 왜 벌벌 떠나…'엡스타인 파일' 억만장자 실체 - 중앙일보",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5jYmItcGo3OGNOT2V0Y2Z4eEtaenVlY0gxTTdwSHltSjBmY29HV3BoeUUwcHp1Y05GSWNESkFRWTB6ZXBrRjkwdlJWNGFmLUIxWmFicHpn?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 24,
    "제목": "백락정 진실규명 뒤집고 신청까지 각하한 진화위…法 “각하는 위법” - 이투데이",
    "추천점수": 7.0,
    "키워드": "진실",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE83UXFOVjI2dnBLREpwREFNbTc3el9DLTZ4eU51dWdhdWF3N3F0ckVwYXlwcm9pUnlfcjRFQjQwdTlvejhHZ0J0eTNURWRnOXBIcEctag?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMihwFBVV95cUxPbmJRelpVTkRpWWFlNklBbkZNTVZyWjRPb3VCTUFwTl9SaXpLTlkyb3ZNQjNWSnFNbTNPbjNrMjBFX1RCOTBDbkRRT1RLeDFoVWtQUFRSaW81c0pud014clM4QmpRaVpjVUNHd1U0N1dkNXVwMXktZjBJNVNmUzN1X1FkYXpxcknSAZsBQVVfeXFMTmFmZEJDaDhGTDZROHBJTDFDdjdLNlczVE0yNjhHZV9xa3ZBcHpBZUVMcy1XZWNHVXU3ZVk4c1RJQVBnTFhzR0xnQmJLLWQ1cUNQc0FMdnJZVHpha1hBRFl0X0ptZ1VadDZUNzlZN3F6OFoyVHBwWENPVmhCU0ZfUTJkQ2pydUNvc0E3MUVBNU8zT1ZrTWc5Y09kWlU?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 25,
    "제목": "\"AI 에이전트가 소프트웨어 삼킨다?\"…투매 부른 공포와 '환각'의 실체 - 글로벌이코노믹",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxNSm5vNndPSXBYWnNIM3p3elo2Z3B5bHcwWmtsU0tnSVBicFhvNG9XU3pkYXc3OXZhSHpDeGE0ZWM3NTgtQ3N1UzBpMEF3dXlKQ1BmbzByMmw0VVd2dFNfUnkxNUlWa1hnS2M4aHQtTG1VNTd1bV8xb2JSanR0QkQ5a0dzcGZ2WWt2?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 26,
    "제목": "법원 \"사형 판결문 발견돼도 집행 불분명하면 진실규명 각하 안돼\" - 아시아경제",
    "추천점수": 7.0,
    "키워드": "진실",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE1jNThnVUN0OS1XcDlqNUlhNlpmcmt3S0dDYmZsRV9HLV9rRkRCSHlxcWdfX2RISXhUMDdqY1Y2bTBlVmFBQmYzZVlMa0RGVG9vd2tCdzVyQlkxbUlyTFBQbw?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 27,
    "제목": "이청아와 불륜 기자 사망… 성매매 앱 실체는? (아너) - 스포츠동아",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibkFVX3lxTE1oSm9RaWljUVhNUEhsTGg4OGFiajVWSkREaU5YTVpvZFVLbndvUUJkRzd2OVMxbFZaTldqMkpubmcxaUh2TWFtd3h5Um94RGxWUzZfeDhJUDNveGNQOEpmQ2p3X3ZaNTRkWko3TWJ3?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 28,
    "제목": "퇴사 통보에 영업비밀 '슬쩍'…17년 '독점 판권' 날아가",
    "추천점수": 7.0,
    "키워드": "비밀",
    "카테고리": "사회",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/055/0001331272?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 29,
    "제목": "늘어나는 정신질환 수용자…치료 못하니 '재범'된다 - 머니투데이",
    "추천점수": 3.0,
    "키워드": "치료",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5SUFJDRXpPQ2RJd0x5eVZ4bmdBRzNBMHNRUURwY09zT19MNVo4RDZvUVM0RkhTVkpfMHZudnVCaHBqRGl4Z0RsbnlkX3loemNFSUtLNFZOMUZHU3hvbEZiTWp5aDBRSnVTcV9j?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 30,
    "제목": "민주, 대한상의 상속세 관련 가짜뉴스 논란에 \"엄중 책임 물어야\" - 뉴시스",
    "추천점수": 3.0,
    "키워드": "논란",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiYEFVX3lxTFBMcmFXNEozNlUzWFdqNVpCcGFMNVFVRFpYQl9rWnJYMm80UVZ5clY4MzFrZmw1Z09jZEhpU3BpcmtNcUtaQUZnSTBEbUFlSFU1d2tuamh6N19Ob29TSXllYtIBeEFVX3lxTE8zTUt4dFJJVWEyZjZMam1zbDlJcmVJdzZjemY0R0R4TzhzVkx2YXIyemlSLXpYVzI3RUhWT1dua1U1cmtwdWU5M21ZbEFOa3ZBUkE4Mm9aMVhXT0I4SGlhNk1pSlB0d3NvMmhoWWh4d0l5V2hkendaag?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  }
];
const scraperStatus = {
  "youtube": "OK",
  "google": "OK",
  "naver": "OK"
};
