const keywordData = [
  {
    "순위": 1,
    "제목": "살아있는 비둘기가 드론 된다…러시아 '생체 드론' 충격 실체 - 전자신문",
    "추천점수": 17.0,
    "키워드": "충격, 실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1zNVpmVjgzcmQ0Z2VtZmVfUXdZaUtESlQ4bldiamU0aTZ1dkJDU3pYcV9jLWRYWFY2WmtMcHVRMHZ2cjZCS1psdGFNd3lSQQ?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 2,
    "제목": "'기어이 중국이 해냈다'…MIT가 폭로한 '무서운 진실' [김리안의 에네르기파WAR]",
    "추천점수": 17.0,
    "키워드": "폭로, 진실",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/015/0005248315?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 3,
    "제목": "[속보]경찰, ‘김병기 의혹’ 관련 국회 사무처 압수수색",
    "추천점수": 17.0,
    "키워드": "속보, 의혹",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.khan.co.kr/article/202602061115001",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 4,
    "제목": "부산 일가족 연쇄사망 미스터리…'그알' 숨겨진 진실 추적 - 노컷뉴스",
    "추천점수": 14.0,
    "키워드": "진실, 숨겨진",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiUkFVX3lxTE5MM3dVSHJqRE14RlpidHhfS1BKRUdCeUlGYU5ueDlPMk1lVFFnN3g0aGlOdHJId0hxOXlDOGJ3a3JHSVAwQml2RUE1NVBIcWJ1UHc?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 5,
    "제목": "[속보]권창영 2차 종합특별검사 “내란 관련 사건이 가장 중요…최선 다해 사건 마무리 하겠다”",
    "추천점수": 13.0,
    "키워드": "속보, 사건",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.khan.co.kr/article/202602060934001",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 6,
    "제목": "[속보]상설특검, 신응석 전 남부지검장·이희동 전 남부지검 차장검사 조사",
    "추천점수": 13.0,
    "키워드": "속보, 조사",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.khan.co.kr/article/202602061031001",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 7,
    "제목": "[속보] 제주공항, 오전 11시부터 운항 재개",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "사회",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/052/0002311948?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 8,
    "제목": "[속보]정부 고위관계자 “쿠팡 미국 ‘청문회’는 로비에 의한 것”",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.khan.co.kr/article/202602060930011",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 9,
    "제목": "\"중국 호텔 침대 몰카에 내가…\" 수천명에 생중계까지 '충격'",
    "추천점수": 10.0,
    "키워드": "충격",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/015/0005248320?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 10,
    "제목": "법원 “충분한 조사 없이 진실규명 신청 각하한 진화위 위법” - 조선일보",
    "추천점수": 10.0,
    "키워드": "진실, 조사",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMihwFBVV95cUxPbmJRelpVTkRpWWFlNklBbkZNTVZyWjRPb3VCTUFwTl9SaXpLTlkyb3ZNQjNWSnFNbTNPbjNrMjBFX1RCOTBDbkRRT1RLeDFoVWtQUFRSaW81c0pud014clM4QmpRaVpjVUNHd1U0N1dkNXVwMXktZjBJNVNmUzN1X1FkYXpxcknSAZsBQVVfeXFMTmFmZEJDaDhGTDZROHBJTDFDdjdLNlczVE0yNjhHZV9xa3ZBcHpBZUVMcy1XZWNHVXU3ZVk4c1RJQVBnTFhzR0xnQmJLLWQ1cUNQc0FMdnJZVHpha1hBRFl0X0ptZ1VadDZUNzlZN3F6OFoyVHBwWENPVmhCU0ZfUTJkQ2pydUNvc0E3MUVBNU8zT1ZrTWc5Y09kWlU?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE83UXFOVjI2dnBLREpwREFNbTc3el9DLTZ4eU51dWdhdWF3N3F0ckVwYXlwcm9pUnlfcjRFQjQwdTlvejhHZ0J0eTNURWRnOXBIcEctag?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 11,
    "제목": "[단독]이즈나 방지민·김재원, '뮤직뱅크' 새 MC…이번에도 女아이돌+男배우 '은행장'",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.sportschosun.com/entertainment/2026-02-06/202602060100041380002715",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 12,
    "제목": "[속보] 해롤드 로저스 쿠팡 대표 “모든 수사에 충실히 협조”···질문엔 ‘묵묵부답’",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.khan.co.kr/article/202602061410021",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 13,
    "제목": "[단독] 최교진 교육부장관 \"16세 선거권 하향, 그 방향으로 가야\"",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0003205220",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 14,
    "제목": "[단독] 윤 정부 '인간정보부대', 정권 교체 뒤에도 추진...시행 직전에 제동",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0003204549",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 15,
    "제목": "‘호남 비하’ 논란에… 김경일 파주시장 “일방적 왜곡, 절대농지 규제 완화 의미” - 문화일보",
    "추천점수": 10.0,
    "키워드": "절대, 논란",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiUEFVX3lxTE1zc1M1TVllMkt5aElMNE9TcVRUVW5WaUJQb2psNGpxOGM2ZTdrZ1FhZUVMOF92eFpkVEN2YjZmRmh5UWdxVkdUUEFCcWUxNHFm?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 16,
    "제목": "\"AI 에이전트가 소프트웨어 삼킨다?\"…투매 부른 공포와 '환각'의 실체 - 글로벌이코노믹",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxNSm5vNndPSXBYWnNIM3p3elo2Z3B5bHcwWmtsU0tnSVBicFhvNG9XU3pkYXc3OXZhSHpDeGE0ZWM3NTgtQ3N1UzBpMEF3dXlKQ1BmbzByMmw0VVd2dFNfUnkxNUlWa1hnS2M4aHQtTG1VNTd1bV8xb2JSanR0QkQ5a0dzcGZ2WWt2?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 17,
    "제목": "백락정 진실규명 뒤집고 신청까지 각하한 진화위…法 “각하는 위법” - 이투데이",
    "추천점수": 7.0,
    "키워드": "진실",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE83UXFOVjI2dnBLREpwREFNbTc3el9DLTZ4eU51dWdhdWF3N3F0ckVwYXlwcm9pUnlfcjRFQjQwdTlvejhHZ0J0eTNURWRnOXBIcEctag?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMihwFBVV95cUxPbmJRelpVTkRpWWFlNklBbkZNTVZyWjRPb3VCTUFwTl9SaXpLTlkyb3ZNQjNWSnFNbTNPbjNrMjBFX1RCOTBDbkRRT1RLeDFoVWtQUFRSaW81c0pud014clM4QmpRaVpjVUNHd1U0N1dkNXVwMXktZjBJNVNmUzN1X1FkYXpxcknSAZsBQVVfeXFMTmFmZEJDaDhGTDZROHBJTDFDdjdLNlczVE0yNjhHZV9xa3ZBcHpBZUVMcy1XZWNHVXU3ZVk4c1RJQVBnTFhzR0xnQmJLLWQ1cUNQc0FMdnJZVHpha1hBRFl0X0ptZ1VadDZUNzlZN3F6OFoyVHBwWENPVmhCU0ZfUTJkQ2pydUNvc0E3MUVBNU8zT1ZrTWc5Y09kWlU?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 18,
    "제목": "시어머니 살해 후 유기한 며느리의 끔찍한 진실 (용형4) - 스포츠동아",
    "추천점수": 7.0,
    "키워드": "진실",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibkFVX3lxTFBId1hJMHVNUmd2eTVKVVBRTmRTeFlkOW9jTlp0WTJFV1otMWY1SjFsVEY0cVVENHFQUDNtOGJqd3RqV3I3cWppVjlMR1JZNEpENHEybXVTUEVENEpvbmxSeEladzRoeEpLXzFvLVpn?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 19,
    "제목": "이청아와 불륜 기자 사망… 성매매 앱 실체는? (아너) - 스포츠동아",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibkFVX3lxTE1oSm9RaWljUVhNUEhsTGg4OGFiajVWSkREaU5YTVpvZFVLbndvUUJkRzd2OVMxbFZaTldqMkpubmcxaUh2TWFtd3h5Um94RGxWUzZfeDhJUDNveGNQOEpmQ2p3X3ZaNTRkWko3TWJ3?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 20,
    "제목": "잘 나가는 거물들 왜 벌벌 떠나…'엡스타인 파일' 억만장자 실체 - 중앙일보",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5jYmItcGo3OGNOT2V0Y2Z4eEtaenVlY0gxTTdwSHltSjBmY29HV3BoeUUwcHp1Y05GSWNESkFRWTB6ZXBrRjkwdlJWNGFmLUIxWmFicHpn?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 21,
    "제목": "연예계 후폭풍 불러온 '법인 절세 전략'…\"관건은 운영 실체\" - 세무사신문",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibkFVX3lxTE9Jd0ZoTGE4ZzZFd1dHWGRXRXVyanUzMEdqaGZHYUVtWnl6VS1ISGpBTmI1Ul9oUmhSM3BrZEU0N09vdGtRQkZ5MUNCelRHamhTTkhPTEZqR3NKS3BlemZ3cGRDNVRtNEw4b3NzV2hB?oc=5",
    "업로드일": "2026-02-05",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 22,
    "제목": "법원 \"사형 판결문 발견돼도 집행 불분명하면 진실규명 각하 안돼\" - 아시아경제",
    "추천점수": 7.0,
    "키워드": "진실",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE1jNThnVUN0OS1XcDlqNUlhNlpmcmt3S0dDYmZsRV9HLV9rRkRCSHlxcWdfX2RISXhUMDdqY1Y2bTBlVmFBQmYzZVlMa0RGVG9vd2tCdzVyQlkxbUlyTFBQbw?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 23,
    "제목": "\"무조건 많이 하라던데\"…아내 돌직구에 고개 숙인 배기성 - 머니투데이",
    "추천점수": 7.0,
    "키워드": "무조건",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMic0FVX3lxTE5FVVVNRExubDBCcUhITG5YelNXT2tzMWp6QTJTbXBqTG9qaldaVVJFZUE2STlxa0Jla2pEeS10TXBTcmh5eHZuYjZLQW80VjRvTEFOakh2ZEhhZzlLdWpScmlXR25wdXpqZ0tQQWdOUzlUc0k?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 24,
    "제목": "“무조건 많이 하라고”…‘배기성 아내’ 이은비, ‘난임 성지’서 49금 질문 폭격 - 매일경제",
    "추천점수": 7.0,
    "키워드": "무조건",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE5nQ3lFSmVHd3RVX25GeFBaYXdyM1JRem9jY05nRWptbkRtZERYVGdWV3gxbXoyTE1mYTdTcFUxejFlMHBiMTg0UERKQi1paWdmaDQ4MUI1UlE0akp3QzBqdzR0OGFuZw?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 25,
    "제목": "‘결혼 9년 차’ 배기성♥이은비, 2세 도전…“무조건 많이 하고”(조선의사랑꾼) - 스포츠동아",
    "추천점수": 7.0,
    "키워드": "무조건",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibkFVX3lxTE51UVNUVU9zWHJub0c0aUYyX3dybWl1QUUtODhmU2lLUTJkNi13eVpUbndVSlpoYTZhOEk4eEpnR3NnOFdJdXVwUU9vVmpIRklkeElvcjA3WUtxcHp2bndlMkkwdjZnbW5rN2otaWNR?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 26,
    "제목": "'배기성♥' 이은비, 난임 성지서 간절함 폭발 \"임신하려면 무조건 많이 깊숙하게…\"(사랑꾼) - 네이트",
    "추천점수": 7.0,
    "키워드": "무조건",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFB5WUFPVkVuVUozN2VuWnptaURVeEthWDVPanpYOFhvSm5CQUpqRUs2N19sRERmT0JaTU13R3JhdzlVeXhqZHJvM3FMZGlkM29HTmow?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 27,
    "제목": "\"절대 추천하지 않는다\"는 Moltbook, 무슨 일 있었나 - 요즘IT",
    "추천점수": 7.0,
    "키워드": "절대",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9kSWF3R0tubGN3MGNiakphNmQzbEp3aUF4S2Nsb3V1TWczOUIzV1pwRDQwS2NxUHNTYmRrM2lUZThTMkZWYnBPNmdERlR2NUlBLUV3T2ZHYXB5dw?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 28,
    "제목": "금융연 \"신용 절대 점수보다 변동 지점 추적 중요\" - 아이뉴스24",
    "추천점수": 7.0,
    "키워드": "절대",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiTEFVX3lxTFBJMVg2NmZlb0pRa0ZIRk5HTlU1NVo0dW9XLWZwTTE1ajlzSkxHY0J2TkVVaVd0QXhCaWtIUURRRjZFNTVzemFrMkdTUTk?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 29,
    "제목": "늘어나는 정신질환 수용자…치료 못하니 '재범'된다 - 머니투데이",
    "추천점수": 3.0,
    "키워드": "치료",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5SUFJDRXpPQ2RJd0x5eVZ4bmdBRzNBMHNRUURwY09zT19MNVo4RDZvUVM0RkhTVkpfMHZudnVCaHBqRGl4Z0RsbnlkX3loemNFSUtLNFZOMUZHU3hvbEZiTWp5aDBRSnVTcV9j?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 30,
    "제목": "수면무호흡증, 양압기 적응 어렵다면? ‘치과적 치료’ 대안 - 스포츠경향",
    "추천점수": 3.0,
    "키워드": "치료",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE9TM0UzU2pnMUswZXRxSC1BMzFlb2tZRmhTek1qVlhFY3I3enJEYW5uMU5tRGRtdUI2ZnVTQkI4UG1fclVVSXhpOVUxSU51MG1JTmZtMmNZZGpDZEdhMHfSAWNBVV95cUxNSXJpMDd3cUtnNTZpRHg3ejdwLTVuM01ST2ctWnVHUVpTb2lvdFY5ajlVZVhkTVpKLS1PcGlhZkxVN1BzSjdldXF0c2Q1SVFXNE5yN0c0QXR5T2JsMGdGTHNfc0E?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  }
];
const scraperStatus = {
  "youtube": "OK",
  "google": "OK",
  "naver": "OK"
};
