const keywordData = [
  {
    "순위": 1,
    "제목": "'우크라 전쟁은 핑계였네' 빵값 원가 충격의 진실 [뉴스.zip/MBC뉴스]",
    "추천점수": 17.0,
    "키워드": "충격, 진실",
    "카테고리": "사회",
    "출처": "유튜브",
    "유튜브_URL": "https://www.youtube.com/watch?v=UVa8jgHfhPg",
    "뉴스기사_URL": "",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": 416868
  },
  {
    "순위": 2,
    "제목": "전 세계가 충격받은 한국 돌다리의 정체 클라스",
    "추천점수": 17.0,
    "키워드": "충격, 정체",
    "카테고리": "사회",
    "출처": "유튜브",
    "유튜브_URL": "https://www.youtube.com/watch?v=l_wrypWacJY",
    "뉴스기사_URL": "",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": 308667
  },
  {
    "순위": 3,
    "제목": "[뉴스'함'] 삼양부터 효성중공업까지..'발칵'... 국민들 분노해야 할 역대급 상황",
    "추천점수": 16.0,
    "키워드": "발칵, 역대급, 분노",
    "카테고리": "사회",
    "출처": "유튜브",
    "유튜브_URL": "https://www.youtube.com/watch?v=YzwrIyWLgrA",
    "뉴스기사_URL": "",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": 121638
  },
  {
    "순위": 4,
    "제목": "홍진경, 딸 라엘 ‘보정 논란’ 폭로…“판빙빙인 줄” - v.daum.net",
    "추천점수": 13.0,
    "키워드": "폭로, 논란",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTE9JQ0Jnbnh1dFdaeUtEMTRRcHNOaXFZNFVrc3ZGMC1SMmVlTm5MUHl3WXkzeGpMZnBRZkFBWjZJM1VoTnNzbTRzVFZkb3hIRkE?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 5,
    "제목": "'CCTV 확인했다, 좋더냐?' 음식 빼돌린 배달 기사 논란 - 네이트",
    "추천점수": 13.0,
    "키워드": "CCTV, 논란",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE1LazBqVG1zMzJmb1RmM3ZIQy1zOHN3dnF1NXJWQUxxUkRJa3RfMUJ2SFdKSHA2MTZFd28xS3NZQnQ4Z2VLZmF6M2I0Y19PR2d1aHpn?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 6,
    "제목": "최강욱 고민정 무대 위 동시 포착! 마이크 잡기 직전 터지는 현장 함성 (김영배 출판기념회)",
    "추천점수": 10.0,
    "키워드": "포착, 현장",
    "카테고리": "사회",
    "출처": "유튜브",
    "유튜브_URL": "https://www.youtube.com/watch?v=1azkwKToR6E",
    "뉴스기사_URL": "",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": 141997
  },
  {
    "순위": 7,
    "제목": "홍진경, 딸 라엘 ‘가짜의 삶’ 폭로…★들도 난리 [DA★] - 스포츠동아",
    "추천점수": 10.0,
    "키워드": "폭로",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibkFVX3lxTE9wVFFDUThuVlJodEUza3B2R0dxeVd3b0N1OE9jMURfeDRtN2FpdEtsS2ZDcWRKZEZHWXluUVc2ZnZLdzVYOFo2YWdZY2ZrZUpKRFVQN1ctckstMjhUVFdEZ1BUNXFiQjNFTXh1dVhn?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 8,
    "제목": "\"저렇게 찍어낼 수 있었어?\".. '초벼락횡재' 투자자 발칵  [뉴스.zip/MBC뉴스]",
    "추천점수": 10.0,
    "키워드": "발칵",
    "카테고리": "사회",
    "출처": "유튜브",
    "유튜브_URL": "https://www.youtube.com/watch?v=L1GQiuBMi60",
    "뉴스기사_URL": "",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": 625930
  },
  {
    "순위": 9,
    "제목": "[단독] 응급실 실려 온 10대…그 뒤엔 AI 있었다",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "사회",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/005/0001830838?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 10,
    "제목": "[단독] 빗썸 ‘62조원 비트코인 오지급 사고’ 막을 수 있었다",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "사회",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/005/0001830958?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 11,
    "제목": "[단독] 국세청, 영장없이 이민자 수천명 개인자산내역 임의 열람했다",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "사회",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/005/0001830959?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 12,
    "제목": "법원 “충분한 조사 없이 진실규명 신청 각하한 진화위 위법” - 조선일보",
    "추천점수": 10.0,
    "키워드": "진실, 조사",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMihwFBVV95cUxPbmJRelpVTkRpWWFlNklBbkZNTVZyWjRPb3VCTUFwTl9SaXpLTlkyb3ZNQjNWSnFNbTNPbjNrMjBFX1RCOTBDbkRRT1RLeDFoVWtQUFRSaW81c0pud014clM4QmpRaVpjVUNHd1U0N1dkNXVwMXktZjBJNVNmUzN1X1FkYXpxcknSAZsBQVVfeXFMTmFmZEJDaDhGTDZROHBJTDFDdjdLNlczVE0yNjhHZV9xa3ZBcHpBZUVMcy1XZWNHVXU3ZVk4c1RJQVBnTFhzR0xnQmJLLWQ1cUNQc0FMdnJZVHpha1hBRFl0X0ptZ1VadDZUNzlZN3F6OFoyVHBwWENPVmhCU0ZfUTJkQ2pydUNvc0E3MUVBNU8zT1ZrTWc5Y09kWlU?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE83UXFOVjI2dnBLREpwREFNbTc3el9DLTZ4eU51dWdhdWF3N3F0ckVwYXlwcm9pUnlfcjRFQjQwdTlvejhHZ0J0eTNURWRnOXBIcEctag?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 13,
    "제목": "빈예서 극찬한 윤명선 가장 아끼는 트로트 가수 정체",
    "추천점수": 7.0,
    "키워드": "정체",
    "카테고리": "사회",
    "출처": "유튜브",
    "유튜브_URL": "https://www.youtube.com/watch?v=y_gzcorcEDo",
    "뉴스기사_URL": "",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": 131998
  },
  {
    "순위": 14,
    "제목": "\"타자마자 미끄러져\"…체어리프트에 매달린 12세 소녀, 결국 추락 #JTBC #Shorts",
    "추천점수": 7.0,
    "키워드": "결국",
    "카테고리": "사회",
    "출처": "유튜브",
    "유튜브_URL": "https://www.youtube.com/watch?v=Uho7iOcK5_Q",
    "뉴스기사_URL": "",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": 178926
  },
  {
    "순위": 15,
    "제목": "법원 \"사형 판결문 발견돼도 집행 불분명하면 진실규명 각하 안돼\" - 아시아경제",
    "추천점수": 7.0,
    "키워드": "진실",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE1jNThnVUN0OS1XcDlqNUlhNlpmcmt3S0dDYmZsRV9HLV9rRkRCSHlxcWdfX2RISXhUMDdqY1Y2bTBlVmFBQmYzZVlMa0RGVG9vd2tCdzVyQlkxbUlyTFBQbw?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 16,
    "제목": "\"AI 에이전트가 소프트웨어 삼킨다?\"…투매 부른 공포와 '환각'의 실체 - 글로벌이코노믹",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxNSm5vNndPSXBYWnNIM3p3elo2Z3B5bHcwWmtsU0tnSVBicFhvNG9XU3pkYXc3OXZhSHpDeGE0ZWM3NTgtQ3N1UzBpMEF3dXlKQ1BmbzByMmw0VVd2dFNfUnkxNUlWa1hnS2M4aHQtTG1VNTd1bV8xb2JSanR0QkQ5a0dzcGZ2WWt2?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 17,
    "제목": "이청아와 불륜 기자 사망… 성매매 앱 실체는? (아너) - 스포츠동아",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibkFVX3lxTE1oSm9RaWljUVhNUEhsTGg4OGFiajVWSkREaU5YTVpvZFVLbndvUUJkRzd2OVMxbFZaTldqMkpubmcxaUh2TWFtd3h5Um94RGxWUzZfeDhJUDNveGNQOEpmQ2p3X3ZaNTRkWko3TWJ3?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 18,
    "제목": "백락정 진실규명 뒤집고 신청까지 각하한 진화위…法 “각하는 위법” - 이투데이",
    "추천점수": 7.0,
    "키워드": "진실",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE83UXFOVjI2dnBLREpwREFNbTc3el9DLTZ4eU51dWdhdWF3N3F0ckVwYXlwcm9pUnlfcjRFQjQwdTlvejhHZ0J0eTNURWRnOXBIcEctag?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMihwFBVV95cUxPbmJRelpVTkRpWWFlNklBbkZNTVZyWjRPb3VCTUFwTl9SaXpLTlkyb3ZNQjNWSnFNbTNPbjNrMjBFX1RCOTBDbkRRT1RLeDFoVWtQUFRSaW81c0pud014clM4QmpRaVpjVUNHd1U0N1dkNXVwMXktZjBJNVNmUzN1X1FkYXpxcknSAZsBQVVfeXFMTmFmZEJDaDhGTDZROHBJTDFDdjdLNlczVE0yNjhHZV9xa3ZBcHpBZUVMcy1XZWNHVXU3ZVk4c1RJQVBnTFhzR0xnQmJLLWQ1cUNQc0FMdnJZVHpha1hBRFl0X0ptZ1VadDZUNzlZN3F6OFoyVHBwWENPVmhCU0ZfUTJkQ2pydUNvc0E3MUVBNU8zT1ZrTWc5Y09kWlU?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 19,
    "제목": "[#언더커버미쓰홍] 드디어 수면 위로 떠오른 예삐의 정체★ 박신혜에게 딱 들킨 한민증권 내부고발자?!😮",
    "추천점수": 7.0,
    "키워드": "정체",
    "카테고리": "사회",
    "출처": "유튜브",
    "유튜브_URL": "https://www.youtube.com/watch?v=BiPmZ9aO9jM",
    "뉴스기사_URL": "",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": 112338
  },
  {
    "순위": 20,
    "제목": "잘 나가는 거물들 왜 벌벌 떠나…'엡스타인 파일' 억만장자 실체 - 중앙일보",
    "추천점수": 7.0,
    "키워드": "실체",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5jYmItcGo3OGNOT2V0Y2Z4eEtaenVlY0gxTTdwSHltSjBmY29HV3BoeUUwcHp1Y05GSWNESkFRWTB6ZXBrRjkwdlJWNGFmLUIxWmFicHpn?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 21,
    "제목": "김용범 “‘국장탈출은 지능순’ 단순 유행어 아냐...좌절·분노 응축\" - 조선일보",
    "추천점수": 3.0,
    "키워드": "분노",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMikAFBVV95cUxPZVVyT0pzNmtFRnRMOHRvSURSUXBfQ0dqY1pqd1puVi0xOGZ4SEloTzBNc1JlcnlaRld1ZExsLTU5U1JRdGM2Sk1Kb1NfQllxa2RnYnp6UlZnR0hUbTdIa1JiM2hScU5nTE5aazdmYy1MM2JsN1VBd3NLY1dyb2hzUGJ0U2Q0dnRxeWJ0UUw0d23SAaQBQVVfeXFMUDBFd0pSZFZUazg0Z3RnWm5UeWhYRTFSUUtJTGhRemgzcGpxUlQxTjc1akFVOVVQdVdVT0lPcVllU1dTUWhrTEdXcjZpbW5WQmpHcVd6ZjNTZnctUko5Y2JsdEkzbTZLZHpHMXppVDRwUWdYYm9XYVd2clZtWnlxWjFGejk0TFJINjhFSzN0OTNQQjB6SHlETTNLem1teU5XTUp0UGw?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 22,
    "제목": "[인터뷰] “HVAC, 삼성의 차세대 핵심 성장 동력”…삼성전자, AI·초연결로 시장 주도권 잡는다",
    "추천점수": 3.0,
    "키워드": "주도권",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.samsung.com/kr/%ec%9d%b8%ed%84%b0%eb%b7%b0-hvac-%ec%82%bc%ec%84%b1%ec%9d%98-%ec%b0%a8%ec%84%b8%eb%8c%80-%ed%95%b5%ec%8b%ac-%ec%84%b1%ec%9e%a5-%eb%8f%99%eb%a0%a5%ec%82%bc%ec%84%b1",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 23,
    "제목": "조국 “민주당 13일까지 입장 없으면 합당 안 할 것”…민주 “10일 의총 후 입장 발표”",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/449/0000334708?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 24,
    "제목": "‘지역 주민 반발에…’ 부산시, 이슬람풍 정원 새 후보지 찾는다",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/082/0001366123?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 25,
    "제목": "서울대 정시 최초합격자 107명 등록 포기… 이공계 대신 의대 쏠림 여전",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/082/0001366113?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 26,
    "제목": "[속보] 빗썸 \"비트코인 오지급 보상 시작…내일부터 수수료 면제\"",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/082/0001366131?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 27,
    "제목": "'똘똘한 한 채' 막을 확실한 방법...이 대통령을 응원합니다",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0003204709",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 28,
    "제목": "경남 찾은 이 대통령 \"심장에만 피·영양 몰리면 살겠나\"",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0003205197",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 29,
    "제목": "버려진 400평 부동산, 그대로 방치했더니 생명이 자라났다",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.khan.co.kr/article/202602061552001",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 30,
    "제목": "2030 청년들이 본 이 대통령·언론 '부동산 설전'...\"5월 9일 이후가 더 중요\"",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0003205166",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  }
];
const scraperStatus = {
  "youtube": "OK",
  "google": "OK",
  "naver": "OK"
};
